services:
  - type: web
    name: campus-hustle-web
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_ALLOWED_HOSTS
        value: 'localhost,127.0.0.1,.onrender.com'
